apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-demo
  namespace: wordpress
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      
  template:
    metadata:
      labels:
        app: mysql
     
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: wordpress
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wordpress
